package infra.keylistenner;
import java.util.HashMap;
import org.jnativehook.keyboard.NativeKeyEvent;

import entities.keyId.KeyId;

public class JNativeKeyIdAdapter {
    static private HashMap<Integer, Integer> jNativeKeyIdToshortcutKeyIdMap;
    static private Boolean hasBuilt = false;

    static public Integer parseJNativeKeyIdToShortcutKeyId(Integer shortcutKeyId) {
        if (JNativeKeyIdAdapter.hasBuilt != true) JNativeKeyIdAdapter.buildHashMaps();
        return JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.get(shortcutKeyId);
    }

    static private void buildHashMaps() {
        JNativeKeyIdAdapter.buildJNativeKeyIdToShortcutKeyIdMap();
        JNativeKeyIdAdapter.hasBuilt = true;
    }

    static private void buildJNativeKeyIdToShortcutKeyIdMap() {
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap = new HashMap<>();
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_ENTER, KeyId.VK_ENTER.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_BACKSPACE, KeyId.VK_BACK_SPACE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_TAB, KeyId.VK_TAB.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SHIFT_L, KeyId.VK_SHIFT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SHIFT_R, KeyId.VK_SHIFT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_CONTROL_L, KeyId.VK_CONTROL.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_CONTROL_R, KeyId.VK_CONTROL.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_ALT_L, KeyId.VK_ALT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_ALT_R, KeyId.VK_ALT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_PAUSE, KeyId.VK_PAUSE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_CAPS_LOCK, KeyId.VK_CAPS_LOCK.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_ESCAPE, KeyId.VK_ESCAPE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SPACE, KeyId.VK_SPACE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_PAGE_UP, KeyId.VK_PAGE_UP.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_PAGE_DOWN, KeyId.VK_PAGE_DOWN.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_END, KeyId.VK_END.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_HOME, KeyId.VK_HOME.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_LEFT, KeyId.VK_LEFT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_UP, KeyId.VK_UP.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_RIGHT, KeyId.VK_RIGHT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_DOWN, KeyId.VK_DOWN.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_COMMA, KeyId.VK_COMMA.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_MINUS, KeyId.VK_MINUS.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_PERIOD, KeyId.VK_PERIOD.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SLASH, KeyId.VK_SLASH.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_0, KeyId.VK_0.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_1, KeyId.VK_1.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_2, KeyId.VK_2.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_3, KeyId.VK_3.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_4, KeyId.VK_4.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_5, KeyId.VK_5.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_6, KeyId.VK_6.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_7, KeyId.VK_7.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_8, KeyId.VK_8.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_9, KeyId.VK_9.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SEMICOLON, KeyId.VK_SEMICOLON.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_EQUALS, KeyId.VK_EQUALS.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_A, KeyId.VK_A.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_B, KeyId.VK_B.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_C, KeyId.VK_C.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_D, KeyId.VK_D.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_E, KeyId.VK_E.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F, KeyId.VK_F.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_G, KeyId.VK_G.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_H, KeyId.VK_H.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_I, KeyId.VK_I.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_J, KeyId.VK_J.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_K, KeyId.VK_K.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_L, KeyId.VK_L.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_M, KeyId.VK_M.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_N, KeyId.VK_N.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_O, KeyId.VK_O.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_P, KeyId.VK_P.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_Q, KeyId.VK_Q.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_R, KeyId.VK_R.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_S, KeyId.VK_S.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_T, KeyId.VK_T.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_U, KeyId.VK_U.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_V, KeyId.VK_V.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_W, KeyId.VK_W.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_X, KeyId.VK_X.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_Y, KeyId.VK_Y.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_Z, KeyId.VK_Z.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_OPEN_BRACKET, KeyId.VK_OPEN_BRACKET.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_BACK_SLASH, KeyId.VK_BACK_SLASH.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_CLOSE_BRACKET, KeyId.VK_CLOSE_BRACKET.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_0, KeyId.VK_NUMPAD0.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_1, KeyId.VK_NUMPAD1.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_2, KeyId.VK_NUMPAD2.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_3, KeyId.VK_NUMPAD3.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_4, KeyId.VK_NUMPAD4.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_5, KeyId.VK_NUMPAD5.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_6, KeyId.VK_NUMPAD6.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_7, KeyId.VK_NUMPAD7.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_8, KeyId.VK_NUMPAD8.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_9, KeyId.VK_NUMPAD9.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_MULTIPLY, KeyId.VK_MULTIPLY.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_ADD, KeyId.VK_ADD.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_SEPARATOR, KeyId.VK_SEPARATER.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_SEPARATOR, KeyId.VK_SEPARATOR.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_SUBTRACT, KeyId.VK_SUBTRACT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KP_DIVIDE, KeyId.VK_DIVIDE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_DELETE, KeyId.VK_DELETE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_NUM_LOCK, KeyId.VK_NUM_LOCK.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SCROLL_LOCK, KeyId.VK_SCROLL_LOCK.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F1, KeyId.VK_F1.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F2, KeyId.VK_F2.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F3, KeyId.VK_F3.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F4, KeyId.VK_F4.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F5, KeyId.VK_F5.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F6, KeyId.VK_F6.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F7, KeyId.VK_F7.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F8, KeyId.VK_F8.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F9, KeyId.VK_F9.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F10, KeyId.VK_F10.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F11, KeyId.VK_F11.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F12, KeyId.VK_F12.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F13, KeyId.VK_F13.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F14, KeyId.VK_F14.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F15, KeyId.VK_F15.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F16, KeyId.VK_F16.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F17, KeyId.VK_F17.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F18, KeyId.VK_F18.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F19, KeyId.VK_F19.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F20, KeyId.VK_F20.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F21, KeyId.VK_F21.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F22, KeyId.VK_F22.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F23, KeyId.VK_F23.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_F24, KeyId.VK_F24.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_PRINTSCREEN, KeyId.VK_PRINTSCREEN.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_INSERT, KeyId.VK_INSERT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_SUN_HELP, KeyId.VK_HELP.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_META_L, KeyId.VK_META.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_META_R, KeyId.VK_META.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_BACKQUOTE, KeyId.VK_BACK_QUOTE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_QUOTE, KeyId.VK_QUOTE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_UP, KeyId.VK_KP_UP.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_DOWN, KeyId.VK_KP_DOWN.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_LEFT, KeyId.VK_KP_LEFT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_RIGHT, KeyId.VK_KP_RIGHT.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_UNDERSCORE, KeyId.VK_UNDERSCORE.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_CONTEXT_MENU, KeyId.VK_CONTEXT_MENU.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KANJI, KeyId.VK_KANJI.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_KATAKANA, KeyId.VK_KATAKANA.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_HIRAGANA, KeyId.VK_HIRAGANA.get());
        JNativeKeyIdAdapter.jNativeKeyIdToshortcutKeyIdMap.put(NativeKeyEvent.VC_UNDEFINED, KeyId.VK_UNDEFINED.get());
    }
}
