package services.shortcuts;
import java.util.HashMap;
import entities.shortcut.ShortcutKeyId;
import org.jnativehook.keyboard.NativeKeyEvent;

// TODO: Parser esta incompleto... conferir cada uma das minhas teclas. Um detalhe,
// os eventos são mapeados no padrão US, e não abnt2... talvez seja interessante
// documentar isso.

public class KeyIdAdapter {
    private HashMap<Integer, Integer> keyIdMap;

    KeyIdAdapter() {
        this.keyIdMap = new HashMap<>();
        this.keyIdMap.put(NativeKeyEvent.VC_ENTER, ShortcutKeyId.VK_ENTER);
        this.keyIdMap.put(NativeKeyEvent.VC_BACKSPACE, ShortcutKeyId.VK_BACK_SPACE);
        this.keyIdMap.put(NativeKeyEvent.VC_TAB, ShortcutKeyId.VK_TAB);
        this.keyIdMap.put(NativeKeyEvent.VC_SHIFT_L, ShortcutKeyId.VK_SHIFT);
        this.keyIdMap.put(NativeKeyEvent.VC_SHIFT_R, ShortcutKeyId.VK_SHIFT);
        this.keyIdMap.put(NativeKeyEvent.VC_CONTROL_L, ShortcutKeyId.VK_CONTROL);
        this.keyIdMap.put(NativeKeyEvent.VC_CONTROL_R, ShortcutKeyId.VK_CONTROL);
        this.keyIdMap.put(NativeKeyEvent.VC_ALT_L, ShortcutKeyId.VK_ALT);
        this.keyIdMap.put(NativeKeyEvent.VC_ALT_R, ShortcutKeyId.VK_ALT);
        this.keyIdMap.put(NativeKeyEvent.VC_PAUSE, ShortcutKeyId.VK_PAUSE);
        this.keyIdMap.put(NativeKeyEvent.VC_CAPS_LOCK, ShortcutKeyId.VK_CAPS_LOCK);
        this.keyIdMap.put(NativeKeyEvent.VC_ESCAPE, ShortcutKeyId.VK_ESCAPE);
        this.keyIdMap.put(NativeKeyEvent.VC_SPACE, ShortcutKeyId.VK_SPACE);
        this.keyIdMap.put(NativeKeyEvent.VC_PAGE_UP, ShortcutKeyId.VK_PAGE_UP);
        this.keyIdMap.put(NativeKeyEvent.VC_PAGE_DOWN, ShortcutKeyId.VK_PAGE_DOWN);
        this.keyIdMap.put(NativeKeyEvent.VC_END, ShortcutKeyId.VK_END);
        this.keyIdMap.put(NativeKeyEvent.VC_HOME, ShortcutKeyId.VK_HOME);
        this.keyIdMap.put(NativeKeyEvent.VC_LEFT, ShortcutKeyId.VK_LEFT);
        this.keyIdMap.put(NativeKeyEvent.VC_UP, ShortcutKeyId.VK_UP);
        this.keyIdMap.put(NativeKeyEvent.VC_RIGHT, ShortcutKeyId.VK_RIGHT);
        this.keyIdMap.put(NativeKeyEvent.VC_DOWN, ShortcutKeyId.VK_DOWN);
        this.keyIdMap.put(NativeKeyEvent.VC_COMMA, ShortcutKeyId.VK_COMMA);
        this.keyIdMap.put(NativeKeyEvent.VC_MINUS, ShortcutKeyId.VK_MINUS);
        this.keyIdMap.put(NativeKeyEvent.VC_PERIOD, ShortcutKeyId.VK_PERIOD);
        this.keyIdMap.put(NativeKeyEvent.VC_SLASH, ShortcutKeyId.VK_SLASH);
        this.keyIdMap.put(NativeKeyEvent.VC_0, ShortcutKeyId.VK_0);
        this.keyIdMap.put(NativeKeyEvent.VC_1, ShortcutKeyId.VK_1);
        this.keyIdMap.put(NativeKeyEvent.VC_2, ShortcutKeyId.VK_2);
        this.keyIdMap.put(NativeKeyEvent.VC_3, ShortcutKeyId.VK_3);
        this.keyIdMap.put(NativeKeyEvent.VC_4, ShortcutKeyId.VK_4);
        this.keyIdMap.put(NativeKeyEvent.VC_5, ShortcutKeyId.VK_5);
        this.keyIdMap.put(NativeKeyEvent.VC_6, ShortcutKeyId.VK_6);
        this.keyIdMap.put(NativeKeyEvent.VC_7, ShortcutKeyId.VK_7);
        this.keyIdMap.put(NativeKeyEvent.VC_8, ShortcutKeyId.VK_8);
        this.keyIdMap.put(NativeKeyEvent.VC_9, ShortcutKeyId.VK_9);
        this.keyIdMap.put(NativeKeyEvent.VC_SEMICOLON, ShortcutKeyId.VK_SEMICOLON);
        this.keyIdMap.put(NativeKeyEvent.VC_EQUALS, ShortcutKeyId.VK_EQUALS);
        this.keyIdMap.put(NativeKeyEvent.VC_A, ShortcutKeyId.VK_A);
        this.keyIdMap.put(NativeKeyEvent.VC_B, ShortcutKeyId.VK_B);
        this.keyIdMap.put(NativeKeyEvent.VC_C, ShortcutKeyId.VK_C);
        this.keyIdMap.put(NativeKeyEvent.VC_D, ShortcutKeyId.VK_D);
        this.keyIdMap.put(NativeKeyEvent.VC_E, ShortcutKeyId.VK_E);
        this.keyIdMap.put(NativeKeyEvent.VC_F, ShortcutKeyId.VK_F);
        this.keyIdMap.put(NativeKeyEvent.VC_G, ShortcutKeyId.VK_G);
        this.keyIdMap.put(NativeKeyEvent.VC_H, ShortcutKeyId.VK_H);
        this.keyIdMap.put(NativeKeyEvent.VC_I, ShortcutKeyId.VK_I);
        this.keyIdMap.put(NativeKeyEvent.VC_J, ShortcutKeyId.VK_J);
        this.keyIdMap.put(NativeKeyEvent.VC_K, ShortcutKeyId.VK_K);
        this.keyIdMap.put(NativeKeyEvent.VC_L, ShortcutKeyId.VK_L);
        this.keyIdMap.put(NativeKeyEvent.VC_M, ShortcutKeyId.VK_M);
        this.keyIdMap.put(NativeKeyEvent.VC_N, ShortcutKeyId.VK_N);
        this.keyIdMap.put(NativeKeyEvent.VC_O, ShortcutKeyId.VK_O);
        this.keyIdMap.put(NativeKeyEvent.VC_P, ShortcutKeyId.VK_P);
        this.keyIdMap.put(NativeKeyEvent.VC_Q, ShortcutKeyId.VK_Q);
        this.keyIdMap.put(NativeKeyEvent.VC_R, ShortcutKeyId.VK_R);
        this.keyIdMap.put(NativeKeyEvent.VC_S, ShortcutKeyId.VK_S);
        this.keyIdMap.put(NativeKeyEvent.VC_T, ShortcutKeyId.VK_T);
        this.keyIdMap.put(NativeKeyEvent.VC_U, ShortcutKeyId.VK_U);
        this.keyIdMap.put(NativeKeyEvent.VC_V, ShortcutKeyId.VK_V);
        this.keyIdMap.put(NativeKeyEvent.VC_W, ShortcutKeyId.VK_W);
        this.keyIdMap.put(NativeKeyEvent.VC_X, ShortcutKeyId.VK_X);
        this.keyIdMap.put(NativeKeyEvent.VC_Y, ShortcutKeyId.VK_Y);
        this.keyIdMap.put(NativeKeyEvent.VC_Z, ShortcutKeyId.VK_Z);
        this.keyIdMap.put(NativeKeyEvent.VC_OPEN_BRACKET, ShortcutKeyId.VK_OPEN_BRACKET);
        this.keyIdMap.put(NativeKeyEvent.VC_BACK_SLASH, ShortcutKeyId.VK_BACK_SLASH);
        this.keyIdMap.put(NativeKeyEvent.VC_CLOSE_BRACKET, ShortcutKeyId.VK_CLOSE_BRACKET);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_0, ShortcutKeyId.VK_NUMPAD0);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_1, ShortcutKeyId.VK_NUMPAD1);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_2, ShortcutKeyId.VK_NUMPAD2);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_3, ShortcutKeyId.VK_NUMPAD3);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_4, ShortcutKeyId.VK_NUMPAD4);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_5, ShortcutKeyId.VK_NUMPAD5);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_6, ShortcutKeyId.VK_NUMPAD6);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_7, ShortcutKeyId.VK_NUMPAD7);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_8, ShortcutKeyId.VK_NUMPAD8);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_9, ShortcutKeyId.VK_NUMPAD9);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_MULTIPLY, ShortcutKeyId.VK_MULTIPLY);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_ADD, ShortcutKeyId.VK_ADD);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_SEPARATOR, ShortcutKeyId.VK_SEPARATER);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_SEPARATOR, ShortcutKeyId.VK_SEPARATOR);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_SUBTRACT, ShortcutKeyId.VK_SUBTRACT);
        this.keyIdMap.put(NativeKeyEvent.VC_KP_DIVIDE, ShortcutKeyId.VK_DIVIDE);
        this.keyIdMap.put(NativeKeyEvent.VC_DELETE, ShortcutKeyId.VK_DELETE);
        this.keyIdMap.put(NativeKeyEvent.VC_NUM_LOCK, ShortcutKeyId.VK_NUM_LOCK);
        this.keyIdMap.put(NativeKeyEvent.VC_SCROLL_LOCK, ShortcutKeyId.VK_SCROLL_LOCK);
        this.keyIdMap.put(NativeKeyEvent.VC_F1, ShortcutKeyId.VK_F1);
        this.keyIdMap.put(NativeKeyEvent.VC_F2, ShortcutKeyId.VK_F2);
        this.keyIdMap.put(NativeKeyEvent.VC_F3, ShortcutKeyId.VK_F3);
        this.keyIdMap.put(NativeKeyEvent.VC_F4, ShortcutKeyId.VK_F4);
        this.keyIdMap.put(NativeKeyEvent.VC_F5, ShortcutKeyId.VK_F5);
        this.keyIdMap.put(NativeKeyEvent.VC_F6, ShortcutKeyId.VK_F6);
        this.keyIdMap.put(NativeKeyEvent.VC_F7, ShortcutKeyId.VK_F7);
        this.keyIdMap.put(NativeKeyEvent.VC_F8, ShortcutKeyId.VK_F8);
        this.keyIdMap.put(NativeKeyEvent.VC_F9, ShortcutKeyId.VK_F9);
        this.keyIdMap.put(NativeKeyEvent.VC_F10, ShortcutKeyId.VK_F10);
        this.keyIdMap.put(NativeKeyEvent.VC_F11, ShortcutKeyId.VK_F11);
        this.keyIdMap.put(NativeKeyEvent.VC_F12, ShortcutKeyId.VK_F12);
        this.keyIdMap.put(NativeKeyEvent.VC_F13, ShortcutKeyId.VK_F13);
        this.keyIdMap.put(NativeKeyEvent.VC_F14, ShortcutKeyId.VK_F14);
        this.keyIdMap.put(NativeKeyEvent.VC_F15, ShortcutKeyId.VK_F15);
        this.keyIdMap.put(NativeKeyEvent.VC_F16, ShortcutKeyId.VK_F16);
        this.keyIdMap.put(NativeKeyEvent.VC_F17, ShortcutKeyId.VK_F17);
        this.keyIdMap.put(NativeKeyEvent.VC_F18, ShortcutKeyId.VK_F18);
        this.keyIdMap.put(NativeKeyEvent.VC_F19, ShortcutKeyId.VK_F19);
        this.keyIdMap.put(NativeKeyEvent.VC_F20, ShortcutKeyId.VK_F20);
        this.keyIdMap.put(NativeKeyEvent.VC_F21, ShortcutKeyId.VK_F21);
        this.keyIdMap.put(NativeKeyEvent.VC_F22, ShortcutKeyId.VK_F22);
        this.keyIdMap.put(NativeKeyEvent.VC_F23, ShortcutKeyId.VK_F23);
        this.keyIdMap.put(NativeKeyEvent.VC_F24, ShortcutKeyId.VK_F24);
        this.keyIdMap.put(NativeKeyEvent.VC_PRINTSCREEN, ShortcutKeyId.VK_PRINTSCREEN);
        this.keyIdMap.put(NativeKeyEvent.VC_INSERT, ShortcutKeyId.VK_INSERT);
        this.keyIdMap.put(NativeKeyEvent.VC_SUN_HELP, ShortcutKeyId.VK_HELP);
        this.keyIdMap.put(NativeKeyEvent.VC_META_L, ShortcutKeyId.VK_META);
        this.keyIdMap.put(NativeKeyEvent.VC_META_R, ShortcutKeyId.VK_META);
        this.keyIdMap.put(NativeKeyEvent.VC_BACKQUOTE, ShortcutKeyId.VK_BACK_QUOTE);
        this.keyIdMap.put(NativeKeyEvent.VC_QUOTE, ShortcutKeyId.VK_QUOTE);
        this.keyIdMap.put(NativeKeyEvent.VC_UP, ShortcutKeyId.VK_KP_UP);
        this.keyIdMap.put(NativeKeyEvent.VC_DOWN, ShortcutKeyId.VK_KP_DOWN);
        this.keyIdMap.put(NativeKeyEvent.VC_LEFT, ShortcutKeyId.VK_KP_LEFT);
        this.keyIdMap.put(NativeKeyEvent.VC_RIGHT, ShortcutKeyId.VK_KP_RIGHT);
        this.keyIdMap.put(NativeKeyEvent.VC_UNDERSCORE, ShortcutKeyId.VK_UNDERSCORE);
        this.keyIdMap.put(NativeKeyEvent.VC_CONTEXT_MENU, ShortcutKeyId.VK_CONTEXT_MENU);
        this.keyIdMap.put(NativeKeyEvent.VC_KANJI, ShortcutKeyId.VK_KANJI);
        this.keyIdMap.put(NativeKeyEvent.VC_KATAKANA, ShortcutKeyId.VK_KATAKANA);
        this.keyIdMap.put(NativeKeyEvent.VC_HIRAGANA, ShortcutKeyId.VK_HIRAGANA);
        this.keyIdMap.put(NativeKeyEvent.VC_UNDEFINED, ShortcutKeyId.VK_UNDEFINED);

        // this.keyIdMap.put(ShortcutKeyId.VK_CANCEL, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_CLEAR, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DECIMAL, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_GRAVE, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_ACUTE, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_CIRCUMFLEX, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_TILDE, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_MACRON, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_BREVE, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_ABOVEDOT, 0);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_DIAERESIS, NativeKeyEvent.VC_DEAD_DIAERESIS);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_ABOVERING, NativeKeyEvent.VC_DEAD_ABOVERING);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_DOUBLEACUTE, NativeKeyEvent.VC_DEAD_DOUBLEACUTE);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_CARON, NativeKeyEvent.VC_DEAD_CARON);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_CEDILLA, NativeKeyEvent.VC_DEAD_CEDILLA);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_OGONEK, NativeKeyEvent.VC_DEAD_OGONEK);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_IOTA, NativeKeyEvent.VC_DEAD_IOTA);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_VOICED_SOUND, NativeKeyEvent.VC_DEAD_VOICED_SOUND);
        // this.keyIdMap.put(ShortcutKeyId.VK_DEAD_SEMIVOICED_SOUND, NativeKeyEvent.VC_DEAD_SEMIVOICED_SOUND);
        // this.keyIdMap.put(ShortcutKeyId.VK_AMPERSAND, NativeKeyEvent.VC_AMPERSAND);
        // this.keyIdMap.put(ShortcutKeyId.VK_ASTERISK, NativeKeyEvent.VC_ASTERISK);
        // this.keyIdMap.put(ShortcutKeyId.VK_QUOTEDBL, NativeKeyEvent.VC_QUOTEDBL);
        // this.keyIdMap.put(ShortcutKeyId.VK_LESS, NativeKeyEvent.VC_LESS);
        // this.keyIdMap.put(ShortcutKeyId.VK_GREATER, NativeKeyEvent.VC_GREATER);
        // this.keyIdMap.put(ShortcutKeyId.VK_BRACELEFT, NativeKeyEvent.VC_BRACELEFT);
        // this.keyIdMap.put(ShortcutKeyId.VK_BRACERIGHT, NativeKeyEvent.VC_BRACERIGHT);
        // this.keyIdMap.put(ShortcutKeyId.VK_AT, NativeKeyEvent.VC_AT);
        // this.keyIdMap.put(ShortcutKeyId.VK_COLON, NativeKeyEvent.VC_COLON);
        // this.keyIdMap.put(ShortcutKeyId.VK_CIRCUMFLEX, NativeKeyEvent.VC_CIRCUMFLEX);
        // this.keyIdMap.put(ShortcutKeyId.VK_DOLLAR, NativeKeyEvent.VC_DOLLAR);
        // this.keyIdMap.put(ShortcutKeyId.VK_EURO_SIGN, NativeKeyEvent.VC_EURO_SIGN);
        // this.keyIdMap.put(ShortcutKeyId.VK_EXCLAMATION_MARK, NativeKeyEvent.VC_EXCLAMATION_MARK);
        // this.keyIdMap.put(ShortcutKeyId.VK_INVERTED_EXCLAMATION_MARK, NativeKeyEvent.VC_INVERTED_EXCLAMATION_MARK);
        // this.keyIdMap.put(ShortcutKeyId.VK_LEFT_PARENTHESIS, NativeKeyEvent.VC_LEFT_PARENTHESIS);
        // this.keyIdMap.put(ShortcutKeyId.VK_NUMBER_SIGN, NativeKeyEvent.VC_NUMBER_SIGN);
        // this.keyIdMap.put(ShortcutKeyId.VK_PLUS, NativeKeyEvent.VC_PLUS);
        // this.keyIdMap.put(ShortcutKeyId.VK_RIGHT_PARENTHESIS, NativeKeyEvent.VC_RIGHT_PARENTHESIS);
        // this.keyIdMap.put(ShortcutKeyId.VK_WINDOWS, NativeKeyEvent.VC_WINDOWS);
        // this.keyIdMap.put(ShortcutKeyId.VK_FINAL, NativeKeyEvent.VC_FINAL);
        // this.keyIdMap.put(ShortcutKeyId.VK_CONVERT, NativeKeyEvent.VC_CONVERT);
        // this.keyIdMap.put(ShortcutKeyId.VK_NONCONVERT, NativeKeyEvent.VC_NONCONVERT);
        // this.keyIdMap.put(ShortcutKeyId.VK_ACCEPT, NativeKeyEvent.VC_ACCEPT);
        // this.keyIdMap.put(ShortcutKeyId.VK_MODECHANGE, NativeKeyEvent.VC_MODECHANGE);
        // this.keyIdMap.put(ShortcutKeyId.VK_KANA, NativeKeyEvent.VC_KANA);
        // this.keyIdMap.put(ShortcutKeyId.VK_ALPHANUMERIC, NativeKeyEvent.VC_ALPHANUMERIC);
        // this.keyIdMap.put(ShortcutKeyId.VK_FULL_WIDTH, NativeKeyEvent.VC_FULL_WIDTH);
        // this.keyIdMap.put(ShortcutKeyId.VK_HALF_WIDTH, NativeKeyEvent.VC_HALF_WIDTH);
        // this.keyIdMap.put(ShortcutKeyId.VK_ROMAN_CHARACTERS, NativeKeyEvent.VC_ROMAN_CHARACTERS);
        // this.keyIdMap.put(ShortcutKeyId.VK_ALL_CANDIDATES, NativeKeyEvent.VC_ALL_CANDIDATES);
        // this.keyIdMap.put(ShortcutKeyId.VK_PREVIOUS_CANDIDATE, NativeKeyEvent.VC_PREVIOUS_CANDIDATE);
        // this.keyIdMap.put(ShortcutKeyId.VK_CODE_INPUT, NativeKeyEvent.VC_CODE_INPUT);
        // this.keyIdMap.put(ShortcutKeyId.VK_JAPANESE_KATAKANA, NativeKeyEvent.VC_JAPANESE_KATAKANA);
        // this.keyIdMap.put(ShortcutKeyId.VK_JAPANESE_HIRAGANA, NativeKeyEvent.VC_JAPANESE_HIRAGANA);
        // this.keyIdMap.put(ShortcutKeyId.VK_JAPANESE_ROMAN, NativeKeyEvent.VC_JAPANESE_ROMAN);
        // this.keyIdMap.put(ShortcutKeyId.VK_KANA_LOCK, NativeKeyEvent.VC_KANA_LOCK);
        // this.keyIdMap.put(ShortcutKeyId.VK_INPUT_METHOD_ON_OFF, NativeKeyEvent.VC_INPUT_METHOD_ON_OFF);
        // this.keyIdMap.put(ShortcutKeyId.VK_CUT, NativeKeyEvent.VC_CUT);
        // this.keyIdMap.put(ShortcutKeyId.VK_COPY, NativeKeyEvent.VC_COPY);
        // this.keyIdMap.put(ShortcutKeyId.VK_PASTE, NativeKeyEvent.VC_PASTE);
        // this.keyIdMap.put(ShortcutKeyId.VK_UNDO, NativeKeyEvent.VC_UNDO);
        // this.keyIdMap.put(ShortcutKeyId.VK_AGAIN, NativeKeyEvent.VC_AGAIN);
        // this.keyIdMap.put(ShortcutKeyId.VK_FIND, NativeKeyEvent.VC_FIND);
        // this.keyIdMap.put(ShortcutKeyId.VK_PROPS, NativeKeyEvent.VC_PROPS);
        // this.keyIdMap.put(ShortcutKeyId.VK_STOP, NativeKeyEvent.VC_STOP);
        // this.keyIdMap.put(ShortcutKeyId.VK_COMPOSE, NativeKeyEvent.VC_COMPOSE);
        // this.keyIdMap.put(ShortcutKeyId.VK_ALT_GRAPH, NativeKeyEvent.VC_ALT_GRAPH);
        // this.keyIdMap.put(ShortcutKeyId.VK_BEGIN, NativeKeyEvent.VC_BEGIN);
        // this.keyIdMap.put(ShortcutKeyId.KEY_LOCATION_UNKNOWN, NativeKeyEvent.KCY_LOCATION_UNKNOWN);
        // this.keyIdMap.put(ShortcutKeyId.KEY_LOCATION_STANDARD, NativeKeyEvent.KCY_LOCATION_STANDARD);
        // this.keyIdMap.put(ShortcutKeyId.KEY_LOCATION_LEFT, NativeKeyEvent.KCY_LOCATION_LEFT);
        // this.keyIdMap.put(ShortcutKeyId.KEY_LOCATION_RIGHT, NativeKeyEvent.KCY_LOCATION_RIGHT);
        // this.keyIdMap.put(ShortcutKeyId.KEY_LOCATION_NUMPAD, NativeKeyEvent.KCY_LOCATION_NUMPAD);
    }

    public Integer parseShortcutKeyIdToNativeKeyId(Integer shortcutKeyId) {
        return this.keyIdMap.get(shortcutKeyId);
    }
}
